sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: brutallesale@gmail.com
node_js:
  - '6'
deploy:
  provider: npm
  email: brutallesale@gmail.com
  api_key: $NPM_TOKEN
  on:
    tags: true

before_install:
  - npm i -g npm@^2.0.0

script:
	- npm run test
after_success:
  - npm run semantic-release
  - npm run coveralls
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
